"use client";
import {useEffect,useState,FormEvent} from "react";
import {ArrowUpRight,ArrowRight,Check,ChevronDown,Package,Ship,TrendingUp,Calculator,ShieldCheck,Plus,Minus,MoveRight} from "lucide-react";
import {landingContent} from "../lib/content";
import {calculate,sample,money} from "../lib/calculator";
const route="/tools/china-import-profit-calculator/calculate";
export function track(name:string){let attribution:Record<string,string>={};try{const stored=JSON.parse(sessionStorage.getItem("zolan_attribution")||"{}");for(const k of ["utm_source","utm_medium","utm_campaign","utm_content","utm_term"])if(typeof stored[k]==="string"&&/^[a-zA-Z0-9_. -]{1,100}$/.test(stored[k]))attribution[k]=stored[k]}catch{}fetch("/api/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,attribution}),keepalive:true}).catch(()=>{})}
const consentText=landingContent.consentText;
const faqs=[
["Is the calculator free?","Yes. You can use the calculator immediately. Email is optional. No payment details are required."],
["Do I need all my quotes before using it?","No. You can start with estimates and update them as you receive supplier, shipping and clearing quotes. Missing costs will make the result provisional."],
["Does it use live exchange rates?","No. Enter the exchange rate available to you so your estimate reflects your own quote."],
["Does it calculate official customs charges?","No. Enter the applicable amounts or your own estimates. Confirm shipment-specific charges and requirements with the relevant authorities and your clearing agent."],
["Does the result show my final net profit?","The calculator shows gross profit, contribution and optional operating estimates. It does not determine final net profit after all financing costs, taxes and accounting adjustments."],
["Can I use it on my phone?","Yes. The calculator is designed for mobile and desktop use."],
["Will I receive marketing emails?","Only if you select the optional checkbox for import tips and Zolan updates. You can unsubscribe from those messages."]];
export default function Landing(){
 const [email,setEmail]=useState("");const [consent,setConsent]=useState(false);const [granted,setGranted]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [errorSource,setErrorSource]=useState("");
 useEffect(()=>{fetch("/api/access").then(r=>r.json() as Promise<{granted:boolean}>).then(b=>setGranted(b.granted)).catch(()=>{});const p=new URLSearchParams(location.search);const a:Record<string,string>={};for(const k of ["utm_source","utm_medium","utm_campaign","utm_content","utm_term"])if(p.has(k))a[k]=p.get(k)!;if(Object.keys(a).length)sessionStorage.setItem("zolan_attribution",JSON.stringify(a));track("landing_viewed")},[]);
 function cta(){track('access_cta_selected');location.href=route;}
 async function submit(e:FormEvent<HTMLFormElement>,source:string){e.preventDefault();if(busy)return;setErrorSource(source);if(!/^\S+@[^\s@]+\.[^\s@]+$/.test(email.trim())){setError("Enter a valid email address.");return}setError("");setBusy(true);try{const website=(new FormData(e.currentTarget)).get("website");let a={};try{a=JSON.parse(sessionStorage.getItem("zolan_attribution")||"{}")}catch{}const r=await fetch("/api/access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,consent,source,website,attribution:a})});const b=await r.json() as {granted:boolean;error?:string};if(!r.ok||!b.granted)throw Error(b.error||"We couldn’t save your email. Please try again.");track("email_captured");location.href=route}catch(err){setError(err instanceof Error?err.message:"We couldn’t save your email. Please try again.");setBusy(false)}}
 function Form({source}:{source:string}){return granted?<div className="returning"><ShieldCheck size={22}/><h3>Your calculator is ready.</h3><a className="button" href={route}>Open calculator <ArrowUpRight size={19}/></a></div>:<form onSubmit={e=>submit(e,source)} noValidate aria-busy={busy}><h3>Email me a calculator access link</h3><label htmlFor={source+"-email"}>Email address</label><div className="email-row"><input id={source+"-email"} name="email" type="email" inputMode="email" autoComplete="email" placeholder="you@example.com" value={email} onChange={e=>{setEmail(e.target.value);setError("")}} required aria-invalid={!!error&&errorSource===source} aria-describedby={error&&errorSource===source?source+"-error":source+"-privacy"}/><button className="button" disabled={busy}>{busy?"Opening your calculator…":"Send link and open calculator"}<ArrowUpRight size={18}/></button></div><input className="honeypot" tabIndex={-1} autoComplete="off" name="website" aria-hidden="true"/>{error&&errorSource===source&&<p className="error" id={source+"-error"} role="alert">{error}</p>}<p className="reassurance"><ShieldCheck size={14}/>Free access. No payment details or password required.</p><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{consentText}</span></label><p className="privacy" id={source+"-privacy"}>We’ll use your email to provide calculator access. See our <a href="https://usezolan.com/privacy" target="_blank" rel="noreferrer">Privacy Policy</a>.</p></form>}
 const r=calculate(sample);
 return <><header><div className="nav wrap"><a href="/" aria-label="Zolan home"><img className="logo" src="/logo.png" alt="Zolan"/></a><div className="navlinks"><a href="#how-it-works">How it works</a><button className="button small" onClick={cta}>{"Open calculator"}<ArrowUpRight size={17}/></button></div></div></header><main>
 <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> FOR BUSINESSES BUYING GOODS FROM CHINA</div><h1>Know what your<br className="desktop-break"/>{" "} China order will<br className="desktop-break"/>{" "} <span>really cost</span><br className="desktop-break"/>{" "} before you pay.</h1><p className="intro">{landingContent.supportingCopy}</p><ul className="ticks"><li><Check/>Include supplier, shipping and import costs.</li><li><Check/>Account for ads, packaging and selling expenses.</li><li><Check/>Compare changes in FX, freight and selling price.</li></ul><div id="access" className="hero-form">{Form({source:"hero"})}</div></div>
 <div className="hero-visual"><div className="route-line"><span>CN <b>China</b></span><span className="route-dash"/><Ship size={18}/><span className="route-dash"/><span>NG <b>Nigeria</b></span></div><div className="preview"><div className="preview-head"><div><span className="tiny">YOUR ORDER, AT A GLANCE</span><h3>From quote to clarity.</h3></div><span className="example-pill">Illustrative example</span></div><div className="order-line"><span className="package-icon"><Package/></span><div><b>100-bag order</b><small>¥40 per bag · ₦220 per yuan</small></div><span className="tag">Sample</span></div><div className="main-result"><span>Landed cost per bag</span><strong>{money(r.landed)}<small>/ bag</small></strong><div className="result-rule"><span/>Supplier + shipping + import costs</div></div><div className="mini-results"><div><span>Selling price</span><strong>₦25,000</strong><small>per bag</small></div><div><span>Contribution per sale</span><strong className="cyan">₦4,400</strong><small>after selling expenses</small></div></div><div className="recovery"><div><span>Cash recovery</span><strong>{r.recovery} <small>sales</small></strong></div><div className="bars">{Array.from({length:20},(_,i)=><i key={i} className={i<16?"filled":""}/>)}</div><small>80 of 100 bags to recover shipment cash</small></div><p className="preview-note">Based on a hypothetical 100-bag order. Replace the figures with your own quotes.</p></div><div className="visual-caption"><Calculator size={17}/><span>Know your costs. Price with a clearer picture.</span></div></div></section>
 <section className="cost-section"><div className="wrap"><div className="section-top"><div><div className="eyebrow">THE FULL PICTURE</div><h2>The supplier price is<br/>{" "}only the beginning.</h2></div><p>That product still needs to get from China to your business in Nigeria. Shipping, import charges, local delivery and selling expenses can change what you actually make.</p></div><div className="cost-flow">{[[Package,"Supplier price","What you pay for the goods"],[Package,"China-side costs","Handling and local transport"],[Ship,"Freight and import charges","Getting your goods to Nigeria"],[TrendingUp,"Selling expenses","Making and fulfilling each sale"]].map(([Icon,title,desc]:any,i)=><div className="cost-step" key={title}><span className="step-number">0{i+1}</span><Icon size={26}/><h3>{title}</h3><p>{desc}</p>{i<3&&<MoveRight className="flow-arrow"/>}</div>)}</div><p className="cost-close">Put the costs together before committing your money. <span>Only include charges that apply to your shipment.</span></p></div></section>
 <section className="benefits wrap"><div className="eyebrow">A BETTER-INFORMED ORDER</div><h2>Make your next order with<br/>{" "}a clearer view of the numbers.</h2><div className="benefit-grid">{[["01","Know what each sellable unit costs.","Bring your supplier price, currency conversion, shipping and import expenses into one calculation."],["02","See what remains after making the sale.","Include packaging, advertising, payment fees and delivery subsidy before judging your margin."],["03","Check the cash commitment.","Estimate your upfront shipment outlay and how many sales could recover it under your assumptions."],["04","Test the order before conditions change.","See what happens if the exchange rate rises, freight costs more or you have to reduce your selling price."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 <section className="example-section wrap"><div className="example-copy"><div className="eyebrow">LET’S PUT NUMBERS TO IT</div><h2>A cheap supplier price<br/>{" "}can hide a very<br/>{" "}different margin.</h2><p>Subtracting the supplier price from the selling price would suggest a much larger return. Adding the import and selling expenses gives you a clearer picture.</p><button className="text-link" onClick={cta}>Calculate my own order <ArrowUpRight size={19}/></button><small>Hypothetical example, not current quotes or applicable tax rates. Contribution is before fixed operating costs, financing and business taxes.</small></div><div className="breakdown"><div className="breakdown-title"><span>THE 100-BAG EXAMPLE</span><span>¥40 × 100 · ₦220/¥</span></div><div className="break-row"><span>Supplier cost per bag</span><strong>₦8,800</strong></div><div className="break-row"><span>China, freight & import costs per bag</span><strong>+ ₦7,800</strong></div><div className="break-row subtotal"><span>Landed cost per sellable bag</span><strong>₦16,600</strong></div><div className="break-row"><span>Selling price</span><strong>₦25,000</strong></div><div className="break-row"><span>Variable selling expenses per sale</span><strong>− ₦4,000</strong></div><div className="break-total"><span>Contribution per sale</span><strong>₦4,400</strong><small>17.6% contribution margin</small></div></div></section>
 <section id="how-it-works" className="how wrap"><div className="eyebrow">HOW IT WORKS</div><h2>From supplier quote<br/>{" "}to a clearer decision.</h2><div className="how-grid">{[["1","Enter your order details.","Add the product price, quantity and exchange rate you expect to pay."],["2","Add your costs.","Include shipping, import expenses and the costs involved in making a sale."],["3","Review and compare.","See estimated landed cost, contribution and cash recovery. Adjust the assumptions to test your order."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 <section className="audience"><div className="wrap"><div className="section-top"><div><div className="eyebrow">FOR THE ORDER YOU’RE PLANNING</div><h2>Built for your<br/>{" "}next China order.</h2></div><p>Whether you’re testing a product, restocking your shop or planning a larger batch, start with the numbers for your own order.</p></div><div className="audience-grid">{[["First order","Check costs before committing."],["Restock","Update your previous assumptions with new quotes."],["Larger batch","Weigh lower unit costs against the cash tied up in stock."]].map(([t,d])=><div key={t}><Plus size={20}/><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
 <section className="payments wrap"><div className="payments-mark"><img src="/mark.png" alt=""/><span>Money across borders.</span></div><div><div className="eyebrow">THE NEXT STEP</div><h2>Planning the order?<br/>{" "}Plan the supplier payment too.</h2><p>The exchange rate and payment costs affect your import numbers from the start. Zolan helps businesses make cross-border payments to Chinese suppliers.</p><div className="payment-actions"><button className="button" onClick={cta}>Open calculator <ArrowUpRight size={18}/></button><a className="text-link" href="https://usezolan.com" onClick={()=>track("supplier_payment_selected")}>Explore supplier payments with Zolan <ArrowUpRight size={17}/></a></div></div></section>
 <section className="faq wrap"><div><div className="eyebrow">GOOD QUESTIONS</div><h2>A little more<br/>{" "}clarity.</h2></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={19}/></summary><p>{a}</p></details>)}</div></section>
 <section className="final"><div className="wrap final-grid"><div><div className="eyebrow">BEFORE THE PAYMENT, DO THE MATH</div><h2>Before you pay your<br/>{" "}supplier, check<br/>{" "}<span>the full cost.</span></h2><p>Use your own order details to estimate landed cost, selling margin and cash recovery.</p></div><div className="final-form">{Form({source:"final"})}</div></div></section>
 </main><footer className="wrap"><div className="footer-top"><a href="/" aria-label="Zolan home"><img className="logo" src="/logo.png" alt="Zolan"/></a><div><a href="https://usezolan.com/privacy">Privacy Policy</a><a href="https://usezolan.com/terms">Terms of Use</a><a href="/tools/china-import-profit-calculator/guide">Import-cost guide</a></div></div><div className="footer-bottom"><p>Results depend on the figures you enter. Estimates are not supplier quotes, customs assessments or guarantees of profit.</p><span>© 2026 Zolan.</span></div></footer></>
}
